name: Keycloak Operator CI

on: [push, pull_request]

env:
  JDK_VERSION: 11

#concurrency:
#  # Only run once for latest commit per ref and cancel other (previous) runs.
#  group: ci-operator-keycloak-${{ github.ref }}
#  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update maven settings
        run: mkdir -p ~/.m2 ; cp .github/settings.xml ~/.m2/
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JDK_VERSION }}
      - name: Cache Maven packages
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
          key: cache-1-${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: cache-1-${{ runner.os }}-m2

      - name: Create the Keycloak distribution
        run: |
          mvn clean install -DskipTests -DskipExamples -DskipTestsuite

      - name: Setup Minikube-Kubernetes
        uses: manusa/actions-setup-minikube@v2.4.3
        with:
          minikube version: v1.24.0
          kubernetes version: v1.22.3
          github token: ${{ secrets.GITHUB_TOKEN }}
          driver: docker
          start args: '--addons=ingress'

      - name: Run minikube tunnel
        run: |
          echo 'Running minikube tunnel'
          minikube tunnel &> /dev/null &
        shell: bash

      - name: Test operator running locally
        working-directory: operator
        run: |
          mvn clean verify \
              -Dit.test=KeycloakIngressE2EIT \
              -Dquarkus.kubernetes.deployment-target=kubernetes
